app/views.py
from flask import render_template, Blueprint, flash, redirect, url_for, request, g, current_app, jsonify
from flask_httpauth import HTTPBasicAuth
from flask_login import current_user, login_user, logout_user, login_required
from flask_socketio import emit
from werkzeug.urls import url_parse

from app.api.auth import auth
from app.emails import send_password_reset_email
from app.forms import LoginForm, RegistrationForm, EditProfileForm, EmptyForm, PostForm, ResetPasswordRequestForm, \
    ResetPasswordForm, SearchForm, MessageForm
from app.models import User, db, Post, Message, Notification
from datetime import datetime
from time import time

log = print

app = Blueprint('views', __name__)


@app.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
        g.search_form = SearchForm()


@app.route('/', methods=['GET', 'POST'])
@app.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(body=form.post.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post is now live!')
        return redirect(url_for('views.index'))
    page = request.args.get('page', 1, type=int)
    posts = current_user.followed_posts().paginate(page, 3, False)
    next_url = url_for('views.index', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('views.index', page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('index.html',
                           title='home',
                           posts=posts.items,
                           form=form,
                           next_url=next_url,
                           prev_url=prev_url
                           )


@app.route('/explore')
@login_required
def explore():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, 3, False)
    log('post', posts)
    next_url = url_for('views.explore', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('views.explore', page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('index.html', title='Explore', posts=posts.items, next_url=next_url, prev_url=prev_url)


@app.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('views.index'))
    form = LoginForm()
    if form.validate_on_submit():

        user = User.one(username=form.username.data)
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('views.login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('views.index')
        return redirect(next_page)
    return render_template('login.html',
                           title='Sign In',
                           form=form,
                           )


@app.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('views.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User.new(form)
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('views.login'))
    return render_template('register.html', title='Register', form=form)


@app.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('views.index'))


@app.route('/user/<username>')
def user(username):
    form = EmptyForm()
    user = User.query.filter_by(username=username).first_or_404()
    log('user', user)
    posts = [
        {'author': user, 'body': 'Test post #1'},
        {'author': user, 'body': 'Test post #2'}
    ]
    return render_template('user.html', user=user, posts=posts, form=form)


@app.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        current_user.save()
        flash('Your changes have been saved.')
        return redirect(url_for('views.edit_profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', title='Edit Profile',
                           form=form)


@app.route('/follow/<username>', methods=['POST'])
@login_required
def follow(username):
    form = EmptyForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=username).first()
        if user is None:
            flash('User {} not found.'.format(username))
            return redirect(url_for('views.index'))
        if user == current_user:
            flash('You cannot follow yourself!')
            return redirect(url_for('views.user', username=username))
        current_user.follow(user)
        db.session.commit()
        flash('You are following {}!'.format(username))
        return redirect(url_for('views.user', username=username))
    else:
        return redirect(url_for('views.index'))


@app.route('/unfollow/<username>', methods=['POST'])
@login_required
def unfollow(username):
    form = EmptyForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=username).first()
        if user is None:
            flash('User {} not found.'.format(username))
            return redirect(url_for('views.index'))
        if user == current_user:
            flash('You cannot unfollow yourself!')
            return redirect(url_for('views.user', username=username))
        current_user.unfollow(user)
        db.session.commit()
        flash('You are not following {}.'.format(username))
        return redirect(url_for('views.user', username=username))
    else:
        return redirect(url_for('views.index'))


@app.route('/reset_password_request', methods=['GET', 'POST'])
def reset_password_request():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = ResetPasswordRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_password_reset_email(user)
        flash('Check your email for the instructions to reset your password')
        return redirect(url_for('views.login'))
    return render_template('reset_password_request.html',
                           title='Reset Password', form=form)


@app.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('views.index'))
    user = User.verify_reset_password_token(token)
    if not user:
        return redirect(url_for('index'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.set_password(form.password.data)
        db.session.commit()
        flash('Your password has been reset.')
        return redirect(url_for('views.login'))
    return render_template('reset_password.html', form=form)


@app.route('/search')
@login_required
def search():
    if not g.search_form.validate():
        return redirect(url_for('main.explore'))
    page = request.args.get('page', 1, type=int)
    posts, total = Post.search(g.search_form.q.data, page,
                               current_app.config['POSTS_PER_PAGE'])

    next_url = url_for('main.search', q=g.search_form.q.data, page=page + 1) \
        if total > page * current_app.config['POSTS_PER_PAGE'] else None
    prev_url = url_for('main.search', q=g.search_form.q.data, page=page - 1) \
        if page > 1 else None
    return render_template('search.html', title='search', posts=posts,
                           next_url=next_url, prev_url=prev_url)


@app.route('/messages')
@login_required
def messages():
    current_user.last_message_read_time = datetime.utcnow()
    current_user.add_notification('unread_message_count', 0)
    db.session.commit()
    page = request.args.get('page', 1, type=int)
    messages = current_user.messages_received.order_by(
        Message.timestamp.desc()).paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('views.messages', page=messages.next_num) \
        if messages.has_next else None
    prev_url = url_for('views.messages', page=messages.prev_num) \
        if messages.has_prev else None
    return render_template('messages.html', messages=messages.items,
                           next_url=next_url, prev_url=prev_url)


@app.route('/send_message/<recipient>', methods=['GET', 'POST'])
@login_required
def send_message(recipient):
    user = User.query.filter_by(username=recipient).first_or_404()
    form = MessageForm()
    if form.validate_on_submit():
        msg = Message(author=current_user, recipient=user,
                      body=form.message.data)
        db.session.add(msg)
        db.session.commit()
        user.add_notification('unread_message_count', user.new_messages())
        db.session.commit()
        flash('Your message has been sent.')
        return redirect(url_for('views.user', username=recipient))

    return render_template('send_message.html', title='Send Message',
                           form=form, recipient=recipient)


@app.route('/notifications')
@login_required
def notifications():
    since = request.args.get('since', 0.0, type=float)
    notifications = current_user.notifications.filter(
        Notification.timestamp > since).order_by(Notification.timestamp.asc())
    return jsonify([{
        'name': n.name,

app/templates/_post.html
<table class="table table-hover">
    <tr>
        <td width="70px">
            <a href="{{ url_for('views.user', username=post.author.username) }}">
                <img src="{{ '' }}"/>
            </a>
        </td>
        <td>
            <a href="{{ url_for('views.user', username=post.author.username) }}">
                {{ post.author.username }}
            </a>
            said {{ moment(post.timestamp).fromNow() }}:
            <br>
            {{ post.body }}
        </td>
    </tr>
</table>

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }} - Microblog{% else %}Welcome to Microblog{% endif %}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('views.index') }}">Microblog</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{{ url_for('views.index') }}">Home</a>
                    </li>
                    <li>
                        <a href="{{ url_for('views.explore') }}">Explore</a>
                    </li>
                </ul>
                {% if g.search_form %}
                    <form class="navbar-form navbar-left" method="get"
                          action="{{ url_for('views.search') }}">
                        <div class="form-group">
                            {{ g.search_form.q(size=20, class='form-control',
                            placeholder=g.search_form.q.label.text) }}
                        </div>
                    </form>
                {% endif %}
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_anonymous %}
                        <li>
                            <a href="{{ url_for('views.login') }}">Login</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{{ url_for('views.messages') }}">
                                Messages
                                {% set new_messages = current_user.new_messages() %}
                                <span id="message_count" class="badge"
                                      style="visibility: {% if new_messages %}visible
                                      {% else %}hidden {% endif %};">
                                {{ new_messages }}
                            </span>
                            </a>
                        </li>
                        <li>
                            <a href="{{ url_for('views.user', username=current_user.username) }}">Profile</a>
                        </li>
                        <li>
                            <a href="{{ url_for('views.logout') }}">Logout</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-info" role="alert">{{ message }}</div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}
        {% endblock %}
    </div>
    {% block scripts %}

        {{ super() }}
        {{ moment.include_moment() }}
        {{ moment.lang(g.locale) }}
        <script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js"
                integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>

        <script>
            $(document).ready(function () {
                var socket = io.connect('//0.0.0.0:5000/');

                function set_message_count(n) {
                    $('#message_count').text(n);
                    $('#message_count').css('visibility', n ? 'visible' : 'hidden');
                }

                {% if current_user.is_authenticated %}
                    $(function () {
                        let since = 0;
                        setInterval(function () {
                            $.ajax('{{ url_for('views.notifications') }}?since=' + since).done(
                                function (notifications) {
                                    for (var i = 0; i < notifications.length; i++) {
                                        if (notifications[i].name == 'unread_message_count')
                                            set_message_count(notifications[i].data);
                                        since = notifications[i].timestamp;
                                    }
                                }
                            );
                        }, 100000);
                    });
                {% endif %}


                {% if current_user.is_authenticated %}
                    socket.on('connect', function () {
                        socket.emit('event', {data: 'I\'m connected!'});
                        socket.on('notification', (notifications) => {
                            console.log('message: ' + JSON.stringify(notifications));
                            for (let i = 0; i < notifications.length; i++) {
                                if (notifications[i].name == 'unread_message_count')
                                    set_message_count(notifications[i].data);
                            }
                        });
                    });
                {% endif %}
            });

        </script>
    {% endblock %}

{% endblock %}

app/templates/edit_profile.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Edit Profile</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.about_me.label }}<br>
            {{ form.about_me(cols=50, rows=4) }}<br>
            {% for error in form.about_me.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block app_content %}
<h1>Hi, {{ current_user.username }}!</h1>
{% if form %}
<form action="" method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.post.label }}<br>
        {{ form.post(cols=32, rows=4) }}<br>
        {% for error in form.post.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>{{ form.submit() }}</p>
</form>

{% endif %}
{% for post in posts %}
{% include '_post.html' %}
{% endfor %}
 <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> Newer posts
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Older posts <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Sign In</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
            <p>New User? <a href="{{ url_for('views.register') }}">Click to Register!</a></p>
 <p>
        Forgot Your Password?
        <a href="{{ url_for('views.reset_password_request') }}">Click to Reset It</a>
    </p>
    </form>
{% endblock %}

app/templates/messages.html
{% extends "base.html" %}

{% block app_content %}
    <h1>{{ 'Messages' }}</h1>
    {% for post in messages %}
        {% include '_post.html' %}
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> {{ 'Newer messages' }}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{ 'Older messages' }} <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Register</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/reset_password.html
<p>Dear {{ user.username }},</p>
<p>
    To reset your password
    <a href="{{ url_for('views.reset_password', token=token, _external=True) }}">
        click here
    </a>.
</p>
<p>Alternatively, you can paste the following link in your browser's address bar:</p>
<p>{{ url_for('views.reset_password', token=token, _external=True) }}</p>
<p>If you have not requested a password reset simply ignore this message.</p>
<p>Sincerely,</p>
<p>The Microblog Team</p>

app/templates/reset_password_request.html
{% extends "base.html" %}

{% block content %}
    <h1>Reset Password</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=64) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/search.html
{% extends "base.html" %}

{% block app_content %}
    <h1>{{ 'Search Results' }}</h1>
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span>
                    {{ 'Previous results' }}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{ 'Next results' }}
                    <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/send_message.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ 'Send Message to {}'.format(recipient) }}</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/user.html
{% extends "base.html" %}

{% block app_content %}
<table>
    <tr valign="top">
        <td>
            <h1>User: {{ user.username }}</h1>

            {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
            {% if user.last_seen %}
            <p>Last seen on: {{ moment(user.last_seen).format('LLL') }}</p>
            {% endif %}
            <p>{{ user.followers.count() }} followers, {{ user.followed.count() }} following.</p>

            {% if user == current_user %}
            <p><a href="{{ url_for('views.edit_profile') }}">Edit your profile</a></p>
            {% elif not current_user.is_following(user) %}
            <p>
            <form action="{{ url_for('views.follow', username=user.username) }}" method="post">
                {{ form.hidden_tag() }}
                {{ form.submit(value='Follow') }}
            </form>
            </p>
            {% else %}
            <p>
            <form action="{{ url_for('views.unfollow', username=user.username) }}" method="post">
                {{ form.hidden_tag() }}
                {{ form.submit(value='Unfollow') }}
            </form>
            </p>
            {% endif %}
        </td>
    </tr>
</table>

<hr>
{% for post in posts %}
<p>
    {{ post.author.username }} says: <b>{{ post.body }}</b>
</p>
{% endfor %}
{% endblock %}